version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: heliodyssee_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - heliodyssee-net

volumes:
  mysql_data:
    name: heliodyssee_mysql_data

networks:
  heliodyssee-net:
    driver: bridge